// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Veyra.Infrastructure.Data.Persistence;

#nullable disable

namespace Veyra.Infrastructure.Data.Persistence.Migrations
{
    [DbContext(typeof(VeyraDbContext))]
    [Migration("20260306143317_AddRepositoriesAndUserProfiles2")]
    partial class AddRepositoriesAndUserProfiles2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("Veyra.Domain.Entities.FileIdentity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "IsDeleted");

                    b.HasIndex("RepositoryId", "RelativePath")
                        .IsUnique();

                    b.ToTable("FileIdentities");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash");

                    b.HasIndex("FilePath");

                    b.ToTable("FileSnapshots");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHashSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeletionMarker")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHashSha256");

                    b.HasIndex("FileIdentityId", "CreatedAt");

                    b.ToTable("FileVersions");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileVersionBlock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BlockHashBlake3")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LengthBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Sequence")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StoredSizeBytes")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BlockHashBlake3");

                    b.HasIndex("FileVersionId", "Sequence")
                        .IsUnique();

                    b.ToTable("FileVersionBlocks");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Repository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalSizeBytes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0L);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("DirectoryId")
                        .IsUnique();

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectoryEntries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FileEntries")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalEntries")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalFileBytes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepositoryId", "CreatedAt");

                    b.ToTable("RepositorySnapshots");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.RepositorySnapshotEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentHashSha256")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDirectory")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastWriteUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentRelativePath")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<string>("RelativePath")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int>("RepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ContentHashSha256");

                    b.HasIndex("RepositoryId", "RelativePath");

                    b.HasIndex("SnapshotId", "ParentRelativePath");

                    b.HasIndex("SnapshotId", "RelativePath")
                        .IsUnique();

                    b.ToTable("RepositorySnapshotEntries");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.SnapshotFileLink", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("FileIdentityId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FileVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SnapshotId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FileVersionId");

                    b.HasIndex("FileIdentityId", "SnapshotId");

                    b.HasIndex("SnapshotId", "FileIdentityId")
                        .IsUnique();

                    b.ToTable("SnapshotFileLinks");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.D_WatchedFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Pattern")
                        .IsUnique();

                    b.ToTable("D_WatchedFormats", (string)null);
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.WatchedDirectory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.ToTable("WatchedDirectories");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.WatchedDirectoryFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FormatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FormatId");

                    b.HasIndex("DirectoryId", "FormatId")
                        .IsUnique();

                    b.ToTable("WatchedDirectoryFormats");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileIdentity", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.Repository", "Repository")
                        .WithMany("FileIdentities")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileVersion", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.FileIdentity", "FileIdentity")
                        .WithMany("Versions")
                        .HasForeignKey("FileIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileIdentity");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileVersionBlock", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.FileVersion", "FileVersion")
                        .WithMany("Blocks")
                        .HasForeignKey("FileVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileVersion");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Repository", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.Watched.WatchedDirectory", "Directory")
                        .WithOne()
                        .HasForeignKey("Veyra.Domain.Entities.Repository", "DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directory");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.Repository", "Repository")
                        .WithMany("Snapshots")
                        .HasForeignKey("RepositoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Repository");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.RepositorySnapshotEntry", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.RepositorySnapshot", "Snapshot")
                        .WithMany("Entries")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.SnapshotFileLink", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.FileIdentity", "FileIdentity")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("FileIdentityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veyra.Domain.Entities.FileVersion", "FileVersion")
                        .WithMany("SnapshotLinks")
                        .HasForeignKey("FileVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veyra.Domain.Entities.RepositorySnapshot", "Snapshot")
                        .WithMany("FileLinks")
                        .HasForeignKey("SnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileIdentity");

                    b.Navigation("FileVersion");

                    b.Navigation("Snapshot");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.WatchedDirectoryFormat", b =>
                {
                    b.HasOne("Veyra.Domain.Entities.Watched.WatchedDirectory", "Directory")
                        .WithMany("DirectoryFormats")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Veyra.Domain.Entities.Watched.D_WatchedFormat", "Format")
                        .WithMany("DirectoryFormats")
                        .HasForeignKey("FormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Directory");

                    b.Navigation("Format");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileIdentity", b =>
                {
                    b.Navigation("SnapshotLinks");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.FileVersion", b =>
                {
                    b.Navigation("Blocks");

                    b.Navigation("SnapshotLinks");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Repository", b =>
                {
                    b.Navigation("FileIdentities");

                    b.Navigation("Snapshots");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.RepositorySnapshot", b =>
                {
                    b.Navigation("Entries");

                    b.Navigation("FileLinks");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.D_WatchedFormat", b =>
                {
                    b.Navigation("DirectoryFormats");
                });

            modelBuilder.Entity("Veyra.Domain.Entities.Watched.WatchedDirectory", b =>
                {
                    b.Navigation("DirectoryFormats");
                });
#pragma warning restore 612, 618
        }
    }
}
