namespace Veyra.Application.DTOs.Repository.Retention;

public sealed record RepositoryRetentionRunResultDto(
    int RepositoryId,
    bool DryRun,
    DateTime StartedAtUtc,
    DateTime FinishedAtUtc,
    bool PolicyApplied,
    bool ArchiveMode,
    int SnapshotsMarked,
    int SnapshotsArchived,
    int ManualSnapshotsMarked,
    int AutomaticSnapshotsMarked,
    int WorkingSnapshotsMarked,
    int AutomaticSnapshotsCompacted,
    int SnapshotEntriesMarked,
    int SnapshotLinksMarked,
    int FileVersionsMarked,
    int FileVersionBlocksMarked,
    int FileIdentitiesMarked,
    int DiffsMarked,
    int DiffHunksMarked,
    int DiffLinesMarked,
    int TextLineAtomsDeleted,
    int BlockFilesDeleted,
    long EstimatedFreedBytes,
    string Summary);
