$map = [ordered]@{
    'Back' = 'common.back'
    'Refresh' = 'common.refresh'
    'Close' = 'common.close'
    'Cancel' = 'common.cancel'
    'Save' = 'common.save'
    'Delete' = 'common.delete'
    'Add' = 'common.add'
    'Browse' = 'common.browse'
    'Open' = 'common.open'
    'Settings' = 'common.settings'
    'Name' = 'common.name'
    'Type' = 'common.type'
    'Size' = 'common.size'
    'Modified' = 'common.modified'
    'Action' = 'common.action'
    'Path' = 'common.path'
    'Version' = 'common.version'
    'Date' = 'common.date'
    'Preview' = 'common.preview'
    'Before' = 'common.before'
    'After' = 'common.after'
    'Running...' = 'common.running'
    'Working...' = 'common.working'
    'VeyraFlow' = 'app.brand'
    'VeyraFlow — ?????????? ?????????' = 'main.window_title'
    '?????????? ?????????' = 'main.product_name'
    'VeyraFlow Desktop' = 'main.product_subtitle'
    'VeyraFlow — Welcome' = 'welcome.window_title'

    'Secure cloud account and sync access' = 'auth.subtitle'
    'Username' = 'auth.username'
    'Enter username' = 'auth.username_placeholder'
    'Password' = 'auth.password'
    'Enter password' = 'auth.password_placeholder'
    'Confirm password' = 'auth.confirm_password'
    'Repeat password' = 'auth.confirm_password_placeholder'
    'Sign in' = 'auth.sign_in'
    'Register' = 'auth.register'

    'Create Repository' = 'dashboard.create_repository'
    'REPOSITORIES' = 'dashboard.repositories_label'
    'Files' = 'dashboard.files'
    'Versions' = 'dashboard.versions'
    'Cloud sync' = 'dashboard.cloud_sync'
    'No repositories yet' = 'dashboard.no_repositories'
    'Create your first repository to start tracking versions.' = 'dashboard.no_repositories_hint'
    'Search by name or path...' = 'dashboard.search_placeholder'

    'Live sync enabled' = 'explorer.live_sync'
    'Rescan files' = 'explorer.rescan_files'
    'Create snapshot' = 'explorer.create_snapshot'
    'Snapshot history' = 'explorer.snapshot_history'
    'Folders' = 'explorer.folders'
    'Search in current folder' = 'explorer.search_current_folder'
    'Pending changes' = 'explorer.pending_changes'
    'No pending changes' = 'explorer.no_pending_changes'
    'Open snapshot history' = 'explorer.open_snapshot_history'
    'Repository tools' = 'explorer.repository_tools'
    'Maintenance actions for damaged or out-of-sync data.' = 'explorer.repository_tools_hint'
    'Fix missing data' = 'explorer.fix_missing_data'
    'Rebuild index' = 'explorer.rebuild_index'
    'Repair links' = 'explorer.repair_links'
    'Selected file' = 'explorer.selected_file'
    'File versions' = 'explorer.file_versions'
    'Loading versions...' = 'explorer.loading_versions'
    'No versions found for selected file.' = 'explorer.no_versions_for_selected_file'
    'No content blocks for selected version. Restore and diff are unavailable.' = 'explorer.no_content_blocks_for_version'
    'Restore as copy' = 'explorer.restore_as_copy'
    'Restore overwrite' = 'explorer.restore_overwrite'
    'Left version' = 'explorer.left_version'
    'Right version' = 'explorer.right_version'
    'Compare in window' = 'explorer.compare_in_window'
    'Select a file from index or snapshot history.' = 'explorer.select_file_from_index'
    'Browse commits, inspect changed files and manage file versions.' = 'explorer.snapshot_history_hint'
    'Commits' = 'explorer.commits'
    'Loading commits...' = 'explorer.loading_commits'
    'No commits yet' = 'explorer.no_commits'
    'Files in selected commit' = 'explorer.files_in_selected_commit'
    'Select a commit to see changed files' = 'explorer.select_commit_for_changes'
    'Loading changed files...' = 'explorer.loading_changed_files'
    'No changed files in this commit' = 'explorer.no_changed_files_in_commit'
    'Version controls' = 'explorer.version_controls'
    'Select a file in commit list to open version controls.' = 'explorer.select_file_for_version_controls'
    'Diff preview' = 'explorer.diff_preview'
    'Diff data is unavailable for this file/version pair.' = 'explorer.diff_data_unavailable'

    '+ Added' = 'diff.added'
    '- Removed' = 'diff.removed'
    '~ Modified' = 'diff.modified'
    '= Context' = 'diff.context'

    'Repository settings' = 'repo_settings.title'
    'Repository name' = 'repo_settings.repository_name'
    'Description' = 'repo_settings.description'
    'Directory path' = 'repo_settings.directory_path'
    'Tracked formats' = 'repo_settings.tracked_formats'
    'Available formats' = 'repo_settings.available_formats'
    'Add custom format' = 'repo_settings.add_custom_format'
    'Conflict strategy' = 'repo_settings.conflict_strategy'
    'Sync status' = 'repo_settings.sync_status'
    'Retry max attempts' = 'repo_settings.retry_max_attempts'
    'Retry base delay (sec)' = 'repo_settings.retry_base_delay_sec'
    'Last successful sync' = 'repo_settings.last_successful_sync'
    'Queue' = 'repo_settings.queue'
    'Sync now' = 'repo_settings.sync_now'
    'Repository bundle' = 'repo_settings.bundle_title'
    'Export current repository data or import a bundle into another folder.' = 'repo_settings.bundle_hint'
    'Export bundle' = 'repo_settings.export_bundle'
    'Import bundle' = 'repo_settings.import_bundle'
    'Retention policy' = 'repo_settings.retention_policy'
    'Enable retention for this repository' = 'repo_settings.enable_retention'
    'Max age (days)' = 'repo_settings.max_age_days'
    'Max snapshots' = 'repo_settings.max_snapshots'
    'Max total size (MB)' = 'repo_settings.max_total_size_mb'
    'Run interval (minutes)' = 'repo_settings.run_interval_minutes'
    'Trigger filter (comma-separated)' = 'repo_settings.trigger_filter'
    'Last run' = 'repo_settings.last_run'
    'Last status' = 'repo_settings.last_status'
    'Dry run' = 'repo_settings.dry_run'
    'Apply retention' = 'repo_settings.apply_retention'
    'example: .sql' = 'repo_settings.example_sql'
    'example: 200' = 'repo_settings.example_200'
    'example: 2048' = 'repo_settings.example_2048'
    'example: 30' = 'repo_settings.example_30'
    'manual_snapshot, sync_live_watcher' = 'repo_settings.trigger_placeholder'

    'Application settings' = 'app_settings.title'
    'User/session controls and pseudo-cloud sync operations.' = 'app_settings.subtitle'
    'Live' = 'app_settings.live_badge'
    'Current session' = 'app_settings.current_session'
    'Active username' = 'app_settings.active_username'
    'Cloud user id' = 'app_settings.cloud_user_id'
    'Token state' = 'app_settings.token_state'
    'Sign out' = 'app_settings.sign_out'
    'Known profiles' = 'app_settings.known_profiles'
    'Token available' = 'app_settings.token_available'
    'Active' = 'app_settings.active'
    'Activate' = 'app_settings.activate'
    'Authentication' = 'app_settings.authentication'
    'Pseudo-cloud sync' = 'app_settings.pseudo_cloud_sync'
    'Cloud API' = 'app_settings.cloud_api'
    'Local repositories' = 'app_settings.local_repositories'
    'Restore from cloud' = 'app_settings.restore_from_cloud'
    'Push all latest snapshots' = 'app_settings.push_all_latest'
    'Process queue' = 'app_settings.process_queue'
    'This tab is reserved for next iteration.' = 'app_settings.placeholder_title'
    'Core user/session and cloud sync settings are fully available in the User and Sync tabs.' = 'app_settings.placeholder_subtitle'

    'Setup Wizard' = 'setup_wizard.window_title'
    'Getting Started' = 'setup_wizard.title'
    'Configure your repository and tracking formats.' = 'setup_wizard.subtitle'
    'Steps' = 'setup_wizard.steps'
    '1. Select directories' = 'setup_wizard.step1'
    '2. Choose formats' = 'setup_wizard.step2'
    '3. Repository name' = 'setup_wizard.step3'

    '??? ???????????' = 'setup.repository_name'
    '???????? ??????-??????' = 'setup.repository_name_example'
    '????? ??????????' = 'setup.select_directories'
    '????? ????? ??? ???????????? ??????' = 'setup.select_directories_subtitle'
    '????????' = 'common.add'
    '???????' = 'common.remove'
    '????? ????????' = 'setup.select_formats'
    '?????? ??????????, ??????? ????? ??????????? ? ????????????' = 'setup.select_formats_subtitle'

    '??? ??? ????????' = 'welcome.what_works'
    '• ???????? ??????????? ? ??????? ????????' = 'welcome.feature_repo'
    '• ??????????? ???????????? ? ???????????' = 'welcome.feature_scan'
    '• ??????? ????????? ?? snapshot' = 'welcome.feature_history'
    '?????? ??????' = 'welcome.get_started'
    '???????? ???????? ???? ????? ?????? ? ??????? ????' = 'welcome.get_started_hint'
    '??????' = 'welcome.start'
    '? ???????' = 'welcome.about'
    '????????????? ?????' = 'welcome.tips_title'
    '????????? ??????? ??????? ?????? ???? ?? ???????? ??????????? ?? ??????? ??????' = 'welcome.tips_subtitle'
    '????????? ????????' = 'welcome.tips_include'
    '• ??????????? ???????????? ?? ????????' = 'welcome.tip_context'
    '• ????????? ?????? ????????????' = 'welcome.tip_errors'
    '• ??????? ???????? ??? ???????????? ? ??????????' = 'welcome.tip_actions'
    '????? ????????' = 'welcome.learning_mode'
    '????? ????????? ????? ? ?????????? ??????????' = 'welcome.learning_mode_hint'
    '???????? ?????????' = 'welcome.enable_tips'
    '??????????' = 'common.continue'

    'Compare Versions' = 'compare.window_title'
    'Version history' = 'compare.version_history'
    'Left click = LEFT side, Right click = RIGHT side' = 'compare.selection_instruction'
    'Selected pair' = 'compare.selected_pair'
    'Building preview...' = 'compare.building_preview'
    'Before version' = 'compare.before_version'
    'After version' = 'compare.after_version'
    'Image preview is not available for this pair.' = 'compare.image_preview_unavailable'
    'No full-file preview data available for this version pair.' = 'compare.no_full_preview'
    'For the most accurate DOC/DOCX comparison (layout, tables, images, and styles), use Open Word compare in Microsoft Word Desktop (2016/2019/2021/Microsoft 365).' = 'compare.word_hint'
    'Open Word compare' = 'compare.open_word_compare'
    'Word compare + styles' = 'compare.word_compare_styles'
    'Open file' = 'compare.open_file'
    'Show in Explorer' = 'compare.show_in_explorer'

    '? ???????' = 'info.window_title'
    'Desktop ???????? ???????? ? ?????????? ?????????' = 'info.subtitle'
    '• ?????????????? ? ?????? ????????????' = 'info.feature_scan_modes'
    '• ??????? ?? snapshot ? ??????????? ??????' = 'info.feature_snapshot_history'
    '• ????????? ???? SQLite' = 'info.feature_sqlite'
    '• ??????????? C# + Rust + Go' = 'info.feature_arch'
    '???????' = 'common.close'

    'Create Snapshot' = 'snapshot_dialog.window_title'
    'Create snapshot' = 'snapshot_dialog.title'
    'Review changed files, set commit name and inspect side-by-side diff before saving.' = 'snapshot_dialog.subtitle'
    'Snapshot name' = 'snapshot_dialog.snapshot_name'
    'snimok_yyyyMMdd_HHmmss' = 'snapshot_dialog.snapshot_name_placeholder'
    'Changed files' = 'snapshot_dialog.changed_files'
    'No changed files detected.' = 'snapshot_dialog.no_changed_files'
    'Diff summary' = 'snapshot_dialog.diff_summary'
    'Scroll: synced' = 'snapshot_dialog.scroll_synced'
    'Pin' = 'snapshot_dialog.pin'
    'Select a modified file to preview text, binary or image-level changes.' = 'snapshot_dialog.select_file_for_preview'
    'Save snapshot' = 'snapshot_dialog.save_snapshot'
}

$files = Get-ChildItem -Recurse -File src/Veyra.Desktop/Views -Include *.axaml
foreach ($file in $files)
{
    $content = Get-Content -Path $file.FullName -Raw

    if ($content -notmatch 'xmlns:loc="clr-namespace:Veyra.Desktop.Localization"')
    {
        $content = $content -replace 'xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"', "xmlns:x=\"http://schemas.microsoft.com/winfx/2006/xaml\"`r`n             xmlns:loc=\"clr-namespace:Veyra.Desktop.Localization\""
    }

    foreach ($entry in $map.GetEnumerator())
    {
        $literal = [regex]::Escape($entry.Key)
        $key = $entry.Value

        foreach ($attr in @('Text','Content','Title','Watermark'))
        {
            $pattern = "${attr}=\"$literal\""
            $replacement = "${attr}=\"{loc:Tr $key}\""
            $content = [regex]::Replace($content, $pattern, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $replacement })
        }
    }

    Set-Content -Path $file.FullName -Value $content
}
